# .github/workflows/build-custom.yml
name: Build custom RustDesk

on:
  workflow_dispatch:

jobs:
  call-custom-windows-build:
    uses: ./.github/workflows/custom-windows-build.yml
    secrets: inherit
